
CREATE TABLE VEM_SER.PAIS (
    ID_PAIS INT PRIMARY KEY NOT NULL, -- Atalho PK
    NOME VARCHAR2(50) UNIQUE NOT NULL
);


CREATE TABLE VEM_SER.ESTADO (
    ID_ESTADO INT NOT NULL,
    ID_PAIS INT NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    PRIMARY KEY (ID_ESTADO) -- Atalho PK
);


CREATE TABLE VEM_SER.CIDADE (
    ID_CIDADE INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    ID_PAIS INT NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY ( ID_CIDADE, ID_ESTADO ),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);


CREATE TABLE VEM_SER.BAIRRO (
	ID_BAIRRO INT NOT NULL,
	ID_CIDADE INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT PK_BAIRRO PRIMARY KEY ( ID_BAIRRO, ID_CIDADE ),
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY ( ID_CIDADE, ID_ESTADO  ) REFERENCES CIDADE( ID_CIDADE, ID_ESTADO )
    CONSTRAINT FK_BAIRRO_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO( ID_ESTADO )
);



CREATE TABLE VEM_SER.BAIRRO (
	ID_BAIRRO INT NOT NULL,
	ID_CIDADE INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    CONSTRAINT PK_BAIRRO PRIMARY KEY ( ID_BAIRRO, ID_CIDADE ),
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY ( ID_CIDADE, ID_ESTADO  ) REFERENCES CIDADE( ID_CIDADE, ID_ESTADO ),
    CONSTRAINT FK_BAIRRO_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO( ID_ESTADO )
);

CREATE TABLE VEM_SER.ENDERECO (
	ID_ENDERECO NUMBER PRIMARY KEY NOT NULL,
	ID_BAIRRO NUMBER NOT NULL,
	ID_CIDADE NUMBER NOT NULL,
	LOGRADOURO VARCHAR2(255) NOT NULL,
	NUMERO NUMBER(38,0) NOT NULL,
	COMPLEMENTO VARCHAR2(100),
	CEP CHAR(9),
	CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO (ID_BAIRRO, ID_CIDADE)
);



SELECT VEM_SER.seq_pessoa.nextval FROM DUAL

SELECT nome
FROM VEM_SER.PESSOA
WHERE nome LIKE '%a';


SELECT
	ID_PESSOA ,
	CPF || ' - ' || NOME AS "CPF - Nome"
FROM
	VEM_SER.PESSOA;

SELECT p.nome 
FROM PAIS p ;


SELECT * 
FROM PAIS p ;


SELECT * 
  FROM PAIS p 
 WHERE UPPER(NOME) LIKE '%A%'
   AND ID_PAIS >= 2;


SELECT * 
  FROM PAIS p 
 ORDER BY NOME ASC;


SELECT *
  FROM ENDERECO 
 WHERE TRIM(CEP) LIKE '%0';

