CREATE USER VEM_SER IDENTIFIED BY oracle;

GRANT CONNECT TO VEM_SER;

GRANT CONNECT, RESOURCE, DBA TO VEM_SER;

GRANT CREATE SESSION TO VEM_SER;

GRANT DBA TO VEM_SER;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO VEM_SER;

GRANT UNLIMITED TABLESPACE TO VEM_SER;
GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
GRANT CREATE TABLE TO VEM_SER;
GRANT GLOBAL QUERY REWRITE TO VEM_SER;
GRANT SELECT ANY TABLE TO VEM_SER;